/* WorksManager 1.9.2 – Stempeluhr mit verschlüsselter Speicherung im state.wm20.
   7:30 normal = 7,50 Industrie-Stunden; Überstunden nach Tages-Soll.
   Automatische Übernahme ins 1.9-Zeitkonto nur, wenn kein fremder Eintrag existiert.
*/
(() => {
'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\'':'&#39;'}[c]));
const uid=()=>crypto.randomUUID?.()||String(Date.now())+Math.random().toString(16).slice(2);
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const pad=n=>String(n).padStart(2,'0');
const time=d=>`${pad(d.getHours())}:${pad(d.getMinutes())}`;
const date=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const hhm=m=>{const sign=m<0?'-':'';m=Math.abs(Math.round(m));return `${sign}${pad(Math.floor(m/60))}:${pad(m%60)}`};
const industrial=m=>(m/60).toLocaleString('de-DE',{minimumFractionDigits:2,maximumFractionDigits:2});
const isOpen=()=>!!$('app')&&!$('app').classList.contains('hidden');
const escapeNumber=(n,min,max)=>{const v=Number(n);if(!Number.isInteger(v)||v<min||v>max)throw Error(`Wert muss eine ganze Zahl zwischen ${min} und ${max} sein.`);return v};
const parseISOTime=(day,clock)=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(day)||!/^\d{2}:\d{2}$/.test(clock))throw Error('Datum oder Uhrzeit ungültig.');const [y,m,d]=day.split('-').map(Number),[h,mi]=clock.split(':').map(Number);if(h>23||mi>59)throw Error('Uhrzeit ungültig.');const dt=new Date(y,m-1,d,h,mi,0);if(dt.getFullYear()!==y||dt.getMonth()!==m-1||dt.getDate()!==d||dt.getHours()!==h||dt.getMinutes()!==mi)throw Error('Nicht existierende Uhrzeit (Zeitumstellung).');return dt};
function compute(a,b,pause){const span=Math.round((new Date(b).getTime()-new Date(a).getTime())/60000);if(!Number.isInteger(span)||span<=0||span>24*60)throw Error('Schichtdauer muss über 0 und höchstens 24 Stunden betragen.');const breaks=escapeNumber(pause,0,1440);if(breaks>=span)throw Error('Pause muss kürzer als die Schichtdauer sein.');return span-breaks}
function store(){if(!state.wm20||typeof state.wm20!=='object'||Array.isArray(state.wm20))state.wm20={};const x=state.wm20;if(!Array.isArray(x.entries))x.entries=[];if(!Number.isInteger(x.targetMinutes)||x.targetMinutes<0||x.targetMinutes>1440)x.targetMinutes=450;if(!x.active||typeof x.active!=='object')x.active=null;return x}
function slotTarget(x){const n=Number(x.targetMinutes);return Number.isInteger(n)&&n>=0&&n<=1440?n:store().targetMinutes}
function overtime(x){return Math.max(0,x.minutes-slotTarget(x))}
function daySummary(rows){const map=new Map();for(const x of rows){const key=x.workDate||date(new Date(x.startAt));if(!map.has(key))map.set(key,[]);map.get(key).push(x)}return [...map].map(([day,arr])=>{const total=arr.reduce((a,r)=>a+r.minutes,0),goal=arr.reduce((v,r)=>Math.max(v,slotTarget(r)),0);return {day,total,goal,overtime:Math.max(0,total-goal),difference:total-goal}}).sort((a,b)=>b.day.localeCompare(a.day))}
const saveSafe=async(message,change)=>{const prev=JSON.stringify(store()),prev19=JSON.stringify(state.wm19??null);change();try{await save(message)}catch(e){state.wm20=JSON.parse(prev);state.wm19=JSON.parse(prev19);throw e}refresh()};
const err=e=>{console.error('Stempeluhr:',e);alert(e?.message||String(e))};
function linkedSync(record){ // Only sync a single session per day; never replace an unrelated manual entry.
 const w=state.wm19;if(!w||!Array.isArray(w.timeRows))return {ok:false,message:'Arbeitszeitkonto noch nicht verfügbar'};
 const day=record.workDate||date(new Date(record.startAt)),sessionRows=store().entries.filter(r=>(r.workDate||date(new Date(r.startAt)))===day);
 if(sessionRows.length!==1)return {ok:false,message:'Mehrere Stempelzeiten für diesen Tag. Übernahme bitte manuell prüfen.'};
 const clashes=w.timeRows.filter(r=>r.date===day&&r.wmClockId!==record.id);
 if(clashes.length)return {ok:false,message:'Für diesen Tag besteht bereits ein Arbeitszeiteintrag. Nichts überschrieben.'};
 const from=new Date(record.startAt),to=new Date(record.endAt);
 let linked=w.timeRows.find(r=>r.wmClockId===record.id);
 if(!linked){linked={id:uid(),date:day,wmClockId:record.id};w.timeRows.push(linked)}
 Object.assign(linked,{date:day,start:time(from),end:time(to),breakMinutes:record.pauseMinutes,note:`Stempeluhr: ${record.note||'automatisch erfasst'}`});
 delete linked.hours;return {ok:true,message:'Ins Arbeitszeitkonto übernommen'};
}
async function start(){if(!isOpen())return;const s=store();if(s.active)throw Error('Die Stempeluhr läuft bereits.');const at=new Date();await saveSafe('Stempeluhr gestartet',()=>{s.active={id:uid(),startAt:at.toISOString(),workDate:date(at),targetMinutes:s.targetMinutes};});}
async function stop(){if(!isOpen())throw Error('Bitte Profil entsperren.');const s=store(),a=s.active;if(!a)throw Error('Die Stempeluhr läuft nicht.');const at=new Date(),pause=escapeNumber($('wmClockPause')?.value||0,0,1440),note=$('wmClockNote')?.value.trim()||'';const minutes=compute(a.startAt,at.toISOString(),pause),record={id:a.id,startAt:a.startAt,endAt:at.toISOString(),workDate:a.workDate||date(new Date(a.startAt)),pauseMinutes:pause,minutes,targetMinutes:a.targetMinutes,note,createdAt:new Date().toISOString()};
 let sync;
 await saveSafe('Stempeluhr gestoppt',()=>{s.active=null;s.entries.push(record);sync=linkedSync(record);});
 if($('wmClockNote'))$('wmClockNote').value='';
 $('wmClockStatus').textContent=`Gestoppt: ${hhm(minutes)} Std. / ${industrial(minutes)} Industriestunden. ${sync?.message||''}`;
}
async function cancelActive(){const s=store();if(!s.active)return;if(!confirm('Laufende Stempelung wirklich verwerfen? Bereits gespeicherte Zeiten bleiben erhalten.'))return;await saveSafe('Laufende Stempelung verworfen',()=>{s.active=null});}
async function saveTarget(){const h=escapeNumber($('wmClockTargetH').value,0,24),m=escapeNumber($('wmClockTargetM').value,0,59);if(h===24&&m)throw Error('Tages-Soll maximal 24 Stunden.');const s=store(),goal=h*60+m;await saveSafe('Tages-Soll gespeichert',()=>{s.targetMinutes=goal;});}
function manualForm(row=null){if(!isOpen())return;const r=row||{startAt:new Date().toISOString(),endAt:new Date().toISOString(),pauseMinutes:30,note:'',targetMinutes:store().targetMinutes},d1=new Date(r.startAt),d2=new Date(r.endAt);
 modal(`<div class="sheet-head"><strong>Stempelzeit ${row?'bearbeiten':'nachtragen'}</strong><button onclick="closeModal()">✕</button></div><form id="wmClockForm" class="wmc-form"><label>Arbeitstag<input name="day" type="date" value="${r.workDate||date(d1)}" required></label><label>Beginn<input name="begin" type="time" value="${time(d1)}" required></label><label>Ende<input name="end" type="time" value="${row?time(d2):time(new Date(d1.getTime()+8*3600000))}" required></label><label>Ende am Folgetag?<select name="next"><option value="auto">Automatisch bei Ende vor Beginn</option><option value="yes" ${row&&date(d1)!==date(d2)?'selected':''}>Ja</option><option value="no">Nein</option></select></label><label>Pause (Minuten)<input name="pause" type="number" min="0" max="1440" step="1" value="${Number(r.pauseMinutes)||0}" required></label><label>Tagessoll (Minuten)<input name="target" type="number" min="0" max="1440" step="1" value="${slotTarget(r)}" required></label><label>Notiz<input name="note" value="${esc(r.note||'')}"></label><button type="submit" class="primary">Speichern</button></form><p class="wmc-small">Nachtschichten werden dem Starttag zugeordnet. Berechnung über die tatsächliche Zeit einschließlich Zeitumstellung.</p>`);
 $('wmClockForm').onsubmit=event=>{event.preventDefault();const btn=event.target.querySelector('button[type=submit]');btn.disabled=true;(async()=>{const f=Object.fromEntries(new FormData(event.target)),startAt=parseISOTime(f.day,f.begin),endAt=parseISOTime(f.day,f.end),pause=escapeNumber(f.pause,0,1440),target=escapeNumber(f.target,0,1440);if(f.next==='yes'||(f.next==='auto'&&endAt<startAt))endAt.setDate(endAt.getDate()+1);const minutes=compute(startAt.toISOString(),endAt.toISOString(),pause),obj={id:row?.id||uid(),startAt:startAt.toISOString(),endAt:endAt.toISOString(),pauseMinutes:pause,targetMinutes:target,minutes,note:String(f.note||'').trim(),createdAt:row?.createdAt||new Date().toISOString()};
 const data=store(),old=JSON.stringify(data),old19=JSON.stringify(state.wm19||null);try{
 if(row){const ix=data.entries.findIndex(x=>x.id===row.id);if(ix<0)throw Error('Eintrag nicht mehr vorhanden.');data.entries[ix]=obj;
 // Editing the date clears old linked time row; do not silently leave old hours in summary.
 if(state.wm19?.timeRows){state.wm19.timeRows=state.wm19.timeRows.filter(x=>x.wmClockId!==row.id)}
 }else data.entries.push(obj);
 const synced=linkedSync(obj);await save('Stempelzeit gespeichert');refresh();closeModal();if($('wmClockStatus'))$('wmClockStatus').textContent=synced.message;
 }catch(e){state.wm20=JSON.parse(old);state.wm19=JSON.parse(old19);throw e}
 })().catch(err).finally(()=>btn.disabled=false)};
}
async function remove(id){const s=store(),r=s.entries.find(x=>x.id===id);if(!r)return;if(!confirm('Stempelzeit löschen? Der Eintrag wird im Stempelzeit-Papierkorb aufgehoben.'))return;await saveSafe('Stempelzeit gelöscht',()=>{s.deleted??=[];s.deleted.push({...r,deletedAt:new Date().toISOString()});s.entries=s.entries.filter(x=>x.id!==id);if(state.wm19?.timeRows)state.wm19.timeRows=state.wm19.timeRows.filter(x=>x.wmClockId!==id)})}
async function restore(id){const s=store(),r=(s.deleted||[]).find(x=>x.id===id);if(!r)return;await saveSafe('Stempelzeit wiederhergestellt',()=>{s.entries.push({...r});s.deleted=s.deleted.filter(x=>x.id!==id);linkedSync(r)})}
function fmtLong(s){return new Date(s).toLocaleString('de-DE',{dateStyle:'short',timeStyle:'short'})}
function renderEntries(){const s=store(),list=$('wmClockEntries');if(!list)return;const month=$('wmClockMonth')?.value||today().slice(0,7),rows=[...s.entries].filter(x=>(x.workDate||date(new Date(x.startAt))).startsWith(month)).sort((a,b)=>b.startAt.localeCompare(a.startAt));const days=daySummary(rows);const mins=rows.reduce((n,x)=>n+x.minutes,0),targets=days.reduce((n,x)=>n+x.goal,0);const extra=days.reduce((n,x)=>n+x.overtime,0),delta=mins-targets;
 $('wmClockMonthSummary').innerHTML=`<div class="wmc-stats"><span><strong>${hhm(mins)}</strong><small>Ist (normal)</small></span><span><strong>${industrial(mins)}</strong><small>Ist (Industrie)</small></span><span><strong>${hhm(extra)}</strong><small>Überstunden</small></span><span><strong>${industrial(extra)}</strong><small>Überstunden Industrie</small></span><span><strong>${hhm(delta)}</strong><small>Saldo inkl. Minusstunden</small></span></div><p class="wmc-small">Soll: ${hhm(targets)} (${industrial(targets)} Industriestunden) für ${days.length} erfasste Arbeitstage. Fehlende Tage werden hier nicht als Minusstunden gezählt.</p>`;
 list.innerHTML=rows.length?rows.map(x=>{const diff=x.minutes-slotTarget(x);return `<div class="wmc-entry"><div><strong>${esc(fmtLong(x.startAt))} – ${esc(time(new Date(x.endAt)))}</strong><small>Ist ${hhm(x.minutes)} = ${industrial(x.minutes)} Industrie · Soll ${hhm(slotTarget(x))} · Differenz ${hhm(diff)} = ${industrial(diff)} Industrie${x.note?' · '+esc(x.note):''}</small></div><div class="wmc-buttons"><button data-wmc-edit="${esc(x.id)}">Bearbeiten</button><button data-wmc-delete="${esc(x.id)}" class="secondary">Löschen</button></div></div>`}).join(''):'<p>Noch keine Stempelzeiten in diesem Monat.</p>';
 const deleted=$('wmClockDeleted');deleted.innerHTML=(s.deleted||[]).length?(s.deleted||[]).slice(-20).reverse().map(r=>`<div class="wmc-entry"><span>${esc(fmtLong(r.startAt))} · ${hhm(r.minutes)}</span><button data-wmc-restore="${esc(r.id)}">Wiederherstellen</button></div>`).join(''):'<p>Keine gelöschten Stempelzeiten.</p>';
}
function live(){if(!$('wmClockLive')||!isOpen())return;const s=store();if(s.active){const start=new Date(s.active.startAt),minutes=Math.max(0,Math.round((Date.now()-start.getTime())/60000));$('wmClockLive').textContent=`Läuft seit ${start.toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})} · ${hhm(minutes)} brutto`;$('wmClockStart').disabled=true;$('wmClockStop').disabled=false}else{$('wmClockLive').textContent='Nicht eingestempelt';$('wmClockStart').disabled=false;$('wmClockStop').disabled=true}}
function refresh(){if(!isOpen())return;const s=store();const h=$('wmClockTargetH'),m=$('wmClockTargetM');if(h&&document.activeElement!==h)h.value=Math.floor(s.targetMinutes/60);if(m&&document.activeElement!==m)m.value=s.targetMinutes%60;live();renderEntries()}
function bind(){const call=f=>()=>Promise.resolve().then(f).catch(err);
 $('wmClockStart').onclick=call(start);$('wmClockStop').onclick=call(stop);$('wmClockSaveTarget').onclick=call(saveTarget);$('wmClockCancel').onclick=call(cancelActive);$('wmClockAdd').onclick=()=>manualForm();$('wmClockMonth').onchange=renderEntries;
 $('wmClockEntries').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.wmcEdit){const r=store().entries.find(x=>x.id===b.dataset.wmcEdit);if(r)manualForm(r)}else if(b.dataset.wmcDelete)call(()=>remove(b.dataset.wmcDelete))()};
 $('wmClockDeleted').onclick=e=>{const b=e.target.closest('[data-wmc-restore]');if(b)call(()=>restore(b.dataset.wmcRestore))()};
}
function mount(){if($('wmClockRoot'))return;const shift=$('shift');if(!shift)return;
 const css=document.createElement('style');css.textContent=`.wmc{margin:16px 0;padding:15px;background:var(--card,#fff);border:1px solid var(--line,#ddd);border-radius:16px;color:var(--ink,#082f4c)}.wmc h3{margin:0 0 10px}.wmc button{border:0;border-radius:8px;padding:10px 12px;background:var(--accent2,#087d79);color:white;font-weight:700;font-size:13px}.wmc button.secondary{background:#eef3f8;color:#1b4058}.wmc-buttons{display:flex;gap:8px;flex-wrap:wrap;margin-top:7px}.wmc-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.wmc label,.wmc-form label{display:flex;flex-direction:column;gap:5px;font-size:12px;font-weight:700}.wmc input,.wmc-form input,.wmc-form select{width:100%;box-sizing:border-box;border:1px solid #b9c8d8;padding:10px;border-radius:8px;font:16px system-ui;color:#12334a;background:white}.wmc-toolbar{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.wmc-stats{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.wmc-stats span{padding:10px;background:#f0f5f8;border-radius:9px}.wmc-stats strong{display:block;font-size:18px}.wmc-stats small,.wmc-entry small{display:block;color:#536e82;font-size:12px;line-height:1.5}.wmc-entry{padding:10px 0;border-bottom:1px solid #dfe7ef}.wmc-small{font-size:12px;color:#596c78;line-height:1.55}.wmc-form{display:grid;gap:10px}.wmc-live{padding:11px 0;font-size:18px;font-weight:800}.wmc-status{font-size:13px;color:#1d6759}@media(max-width:520px){.wmc-grid{grid-template-columns:minmax(0,1fr)}.wmc-stats{grid-template-columns:repeat(2,minmax(0,1fr))}}`;
 document.head.appendChild(css);const panel=document.createElement('section');panel.id='wmClockRoot';panel.className='wmc';panel.innerHTML=`<h3>Stempeluhr</h3><p class="wmc-small">Start/Stopp oder Zeiten nachtragen. Zeitangaben bleiben im aktiven verschlüsselten Profil.</p><div id="wmClockLive" class="wmc-live">Nicht eingestempelt</div><div class="wmc-grid"><label>Pause beim Stoppen (Minuten)<input type="number" id="wmClockPause" min="0" max="1440" step="1" value="30"></label><label>Notiz<input id="wmClockNote" placeholder="z. B. Frühschicht"></label></div><div class="wmc-toolbar"><button type="button" id="wmClockStart">Start</button><button type="button" id="wmClockStop" class="secondary">Stopp</button><button type="button" id="wmClockAdd" class="secondary">Zeit nachtragen</button><button type="button" id="wmClockCancel" class="secondary">Laufende Zeit verwerfen</button></div><p id="wmClockStatus" class="wmc-status" aria-live="polite"></p><h3>Täglich zu leistende Arbeitszeit</h3><div class="wmc-grid"><label>Stunden<input type="number" id="wmClockTargetH" min="0" max="24" value="7"></label><label>Minuten<input type="number" id="wmClockTargetM" min="0" max="59" value="30"></label></div><div class="wmc-toolbar"><button id="wmClockSaveTarget" type="button">Tages-Soll speichern</button></div><p class="wmc-small">Beispiel: 7:30 Uhr = 7,50 Industriestunden; 30 Minuten Überstunden = 0,50 Industriestunden. Der Monats-Saldo berücksichtigt auch Minusstunden.</p><label>Monat auswählen<input type="month" id="wmClockMonth" value="${today().slice(0,7)}"></label><div id="wmClockMonthSummary"></div><h3>Gestempelte Zeiten</h3><div id="wmClockEntries"></div><details><summary>Gelöschte Stempelzeiten</summary><div id="wmClockDeleted"></div></details>`;
 const anchor=$('wm19TimeCard');if(anchor)anchor.insertAdjacentElement('afterend',panel);else shift.appendChild(panel);bind();refresh();
 let ref=state;if(typeof window.renderAll==='function'){const previous=window.renderAll;window.renderAll=function(...args){const changed=state!==ref;const result=previous.apply(this,args);if(changed)ref=state;setTimeout(refresh,0);return result}}
 const updateTitle=$('wmplusQuickUpdateCheck')?.closest('#wmplusQuickUpdateBar')?.querySelector('strong');if(updateTitle)updateTitle.textContent='App-Updates · WorksManager 1.9.2';
 window.addEventListener('pageshow',()=>setTimeout(refresh,150));setInterval(live,15000);console.info('WorksManager Stempeluhr 1.9.2 geladen');
}
if(typeof module!=='undefined'&&module.exports)module.exports={compute,hhm,industrial,daySummary,parseISOTime};
else if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})();
